version: '{build}'
image: Visual Studio 2015

branches:
  only:
  - master

pull_requests:
  do_not_increment_build_number: true

build_script:
- ps: .\build.ps1

artifacts:
- path: '.\artifacts\*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: tHjfRzg82jtCm5KBH8GCYMivXja69L7S3NxPM7pIUi49T4auTZZ3N9hcbzAQmNHi
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
      branch: /^(master)$/
